name: isolate_channel
description: Communication channels for isolates based on Flutter's plugin channels
homepage: https://github.com/IO-Design-Team/isolate_channel
version: 0.5.0

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.14.0

dev_dependencies:
  test: ^1.24.0
  rexios_lints: ^17.0.2
  mockito: ^5.4.5
  build_runner: ^2.4.15
